const images = {
    jackySection1: "/images/jacky/Jacklyn10b.jpg",
    jackySection2: "/images/jacky/Jacklyn6.jpg",
    JackySection3: "/images/jacky/Jacklyn9.jpg",
    AboutJacky1: "/images/jacky/Jacklyn7.jpg",
    jackyWithDog: "/images/jacky/Jacklyn1.jpg",
    jackyAcne: "/images/jacky/jacky-acne.jpg",
    jackyAcneHealed: "/images/jacky/jacky-acne-healed.jpg",
    jackyParkRanger: "/images/jacky/jacky-park-ranger-blur.jpg",
    nielsOllie: "/images/jacky/niels-ollie.jpg",
    jackyNielsBeach: "/images/jacky/Jacklyn-Niels-tenerife-wedding.jpg",
    jackyWithNotepad: "/images/jacky/Jacklyn2.jpg",

    yhypLogo: "/images/ayurveda/yhyp-nobackground-modified.png",
    yhypTextLogo: "/images/ayurveda/yhyp-logo_processed.jpg",
    yhypLogoOutline: "/images/ayurveda/yhyp-green_processed.jpg",
    yhypLogoNoBackground: "/images/ayurveda/yhyp-nobackground-coral.png",
    coffeeWithBook: "/images/cwb.jpg",
    walkYourPath: "/images/walk-your-path.jpg",
    womanOnLaptop: "/images/woman-on-laptop.jpg",
    massage: "/images/massage.jpg",
    noteTaking: "/images/note-taking.jpg",
    pool: "/images/pool.jpg",
    holistic: "/images/holistic.jpg",
    plantOnTable: "/images/plant-table.jpg",
    pinkFlower: "/images/pink-flower.jpg",
    purpleFlowers: "/images/purple-flowers.jpg",
    massageTools: "/images/massage-tools.png",
    pageBreak: "/images/decorative-separator.png",
    dancing: "images/dancing.jpg",
    flowers: "images/flowers.jpg",
    orangeFlowers: "/images/orange-flowers.jpg",
    spices: '/images/spices.jpg',
    mountainLake: "/images/mountain-lake.jpg",
    mountainColorful: "/images/mountain-colors.jpg",
    meditate: "/images/meditate.jpg",
    whatsApp: "/images/whatsapp.png",


    //ayurveda page pictures
    marketSpices: '/images/market-spices.jpg',
    asana: '/images/ayurveda/asana.jpg',
    air: '/images/ayurveda/air.jpg',
    fire: '/images/ayurveda/fire.jpg',
    earth: '/images/ayurveda/earth.jpg',
    water: '/images/ayurveda/water.jpg',
    gmaD: '/images/ayurveda/gmad.jpg',
    gmaM: '/images/ayurveda/gmam.jpg'
}

export default images;