const images = {
    jackySection1: "/images/jacky/jacky10b.webp",
    jackySection2: "/images/jacky/Jacklyn6.jpg",
    JackySection3: "/images/jacky/Jacklyn9.webp",
    AboutJacky1: "/images/jacky/Jacklyn7.webp",
    jackyWithDog: "/images/jacky/Jacklyn1.jpg",
    jackyAcne: "/images/jacky/jacky-acne.jpg",
    jackyAcneHealed: "/images/jacky/jacky-acne-healed.jpg",
    jackyParkRanger: "/images/jacky/jacky-park-ranger-blur.jpg",
    nielsOllie: "/images/jacky/niels-ollie.jpg",
    jackyNielsBeach: "/images/jacky/Jacklyn-Niels-tenerife-wedding.webp",
    jackyWithNotepad: "/images/jacky/Jacklyn2.webp",

    yhypLogo: "/images/ayurveda/yhyp-nobackground-modified.webp",
    yhypTextLogo: "/images/ayurveda/yhyp-logo_processed.webp",
    yhypLogoOutline: "/images/ayurveda/yhyp-green_processed.jpg",
    yhypLogoNoBackground: "/images/ayurveda/yhyp-nobackground-coral.png",
    yhypGreenNoBackground: "/images/ayurveda/yhyp-green-nobackground.png",
    yhypWhiteNoBackground: "/images/ayurveda/yhyp-white-nobackground.png",
    coffeeWithBook: "/images/cwb.jpg",
    walkYourPath: "/images/walk-your-path.jpg",
    womanOnLaptop: "/images/woman-on-laptop.webp",
    massage: "/images/massage.webp",
    noteTaking: "/images/note-taking.webp",
    pool: "/images/pool.jpg",
    holistic: "/images/holistic.webp",
    plantOnTable: "/images/plant-table.jpg",
    pinkFlower: "/images/pink-flower.jpg",
    purpleFlowers: "/images/purple-flowers.jpg",
    massageTools: "/images/massage-tools.webp",
    pageBreak: "/images/decorative-separator.png",
    dancing: "/images/dancing.webp",
    spices: '/images/spices2.webp',
    mountainLake: "/images/mountain-lake.webp",
    mountainColorful: "/images/mountain-colors.jpg",
    meditate: "/images/meditate.webp",
    whatsApp: "/images/whatsapp.webp",
    signalLogo: "/images/signalLogo.webp",
    plants: "/images/plants.webp",
    path: "public/images/pathway.webp",
    pinkFlowers: "images/pink-flowers.jpg",
    pinkFlowers2: "images/pink-flowers2.jpg",
    forest: "/images/forest.jpg",
    treeRooted: "/images/tree-rooted.jpg",
    soupWithSpices: "/images/soup-with-spices.webp",
    womanStretching: "/images/woman-stretching.webp",
    massageWoman: "/images/massage-woman.webp",
    massageFoot: "/images/massage-foot.webp",
    space: "/images/space.webp",
    purpleFlowers2: "/images/purple-flowers2.jpg",



    //ayurveda page pictures
    marketSpices: '/images/market-spices.jpg',
    asana: '/images/ayurveda/asana.webp',
    air: '/images/ayurveda/air.webp',
    fire: '/images/ayurveda/fire.webp',
    earth: '/images/ayurveda/earth.webp',
    water: '/images/ayurveda/water.webp',
    gmaD: '/images/ayurveda/gmad.jpg',
    gmaM: '/images/ayurveda/gmam.jpg',
    yhypIcon: "/images/ayurveda/yhyp-icon.png"
}

export default images;